Upgrade spring to latest stable,
and hsqldb, and dokumenttipalvelu-service junit to same as others.
Minor tweaks were needed in the upgrade.
Let's hope this fixes

Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [fi.vm.sade.security.CustomCasAuthenticationFilter]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.util.AntPathMatcher.setCaseSensitive(Z)V