Harmonise cglib dependencies so we have only cglib:cglib-nodep:jar:2.2.2
valintalaskenta-laskenta-service got this on startup:
Failed to instantiate
[org.mongodb.morphia.Morphia]: Factory method 'getMorphia' threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer